# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeightScale' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeightScale
  pod 'Firebase/AdMob'
  pod 'Firebase/Analytics'
  pod 'Google-Mobile-Ads-SDK'

  pod 'PureLayout'
  pod 'BrightFutures'
  pod 'Charts'
  pod 'RealmSwift'

  target 'WeightScaleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Succinct'
    pod 'Quick'
    pod 'Nimble'
  end

  target 'WeightScaleThirdPartyAPITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Succinct'
    pod 'Quick'
    pod 'Nimble'
  end

end
