update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :unittests do
  scan(
    device: "iPhone 12",
    clean: true,
    scheme: "WeightScale"
  )
  end

  lane :beta do
    # carthage(platform: "iOS", use_binaries: false, cache_builds: true)

    unittests

    increment_build_number
    commit_version_bump
    push_to_git_remote

    build_app(workspace: "WeightScale.xcworkspace", scheme: "WeightScale Release")

    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
